version: "3"

services:
    influxdb:
        build: ./influxdb
        ports:
            - ${INFLUXDB_PORT}:${INFLUXDB_PORT}
        volumes:
            - tig-influxdb:/var/lib/influxdb
        restart: always
        env_file:
            - .env
              #        networks:
              #- backend
              # - nginx

    telegraf:
        build: ./telegraf
        links:
            - influxdb
            - mongodb
            - nginx
            - elastic
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /proc:/hostfs/proc
        privileged: true
        restart: always
        env_file:
            - .env
              #        networks: 
              #            - nginx
              #            - backend
            
    grafana:
        build: ./grafana
        container_name: grafana
          #       ports: 
          #- ${GRAFANA_PORT}:${GRAFANA_PORT}
        links:
            - influxdb
        volumes:
          - tig-grafana:/var/lib/grafana
          - /var/log/grafana
        restart: always
        env_file:
            - .env
              #        networks:
              #            - nginx

    nginx:
        build: ./nginx
        container_name: nginx
        ports: 
            - 8080:8080
            - 8081:8081
            - 8082:8082
        links:
            - influxdb
            - grafana
            - application
        restart: always
        env_file:
            - .env
              #        networks:
          #            - frontend
              #            - backend
              #            - nginx

    mongodb:
        image: mongo
        volumes:
          - tig-mongodb:/data
        ports: 
          - 27017:27017
        restart: always
        env_file:
            - .env
              #        networks:
          #            - backend

    application:
        build: ./application
        container_name: application
        ports: 
          - 8000:8000
        links:
          - mongodb
          - elastic
        restart: always
        env_file:
            - .env
              #        networks:
          #            - backend
              #            - frontend

    elastic:
        build: ./elasticsearch
        container_name: elastic
        volumes: 
          - tig-elastic:/usr/share/elasticsearch/data
        ports: 
          - 9200:9200
        restart: always
        env_file:
            - .env
              #        networks:
              #            - backend
volumes:
  tig-grafana: 
  tig-influxdb: 
  tig-mongodb: 
  tig-elastic: 

